/* Generated By:JJTree&JavaCC: Do not edit this line. LPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int APARENTESES = 7;
  /** RegularExpression Id. */
  int FPARENTESES = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int VOID = 14;
  /** RegularExpression Id. */
  int PVIRGULA = 15;
  /** RegularExpression Id. */
  int SOMA = 16;
  /** RegularExpression Id. */
  int SUBTRACAO = 17;
  /** RegularExpression Id. */
  int DIVISAO = 18;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 19;
  /** RegularExpression Id. */
  int ATRIBUICAO = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int RETURN = 26;
  /** RegularExpression Id. */
  int IGUALDADE = 27;
  /** RegularExpression Id. */
  int DIFERENTE = 28;
  /** RegularExpression Id. */
  int MAIOR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIORIGUAL = 31;
  /** RegularExpression Id. */
  int MENORIGUAL = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int ATRIBUICAOSOMA = 34;
  /** RegularExpression Id. */
  int ATRIBUICAOSUBTRACAO = 35;
  /** RegularExpression Id. */
  int INC = 36;
  /** RegularExpression Id. */
  int DEC = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int NUM = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"void\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"=\"",
    "\"print\"",
    "\"for\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"return\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\",\"",
    "\"+=\"",
    "\"-=\"",
    "\"++\"",
    "\"--\"",
    "<ID>",
    "<NUM>",
  };

}
