/* Generated By:JavaCC: Do not edit this line. LPTreeConstants.java Version 5.0 */
public interface LPTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTTOKENCOMPARADOR = 1;
  public int JJTTYPE = 2;
  public int JJTCOMANDOS = 3;
  public int JJTVAR = 4;
  public int JJTIDORVALUE = 5;
  public int JJTFOR = 6;
  public int JJTPARAMETERSFOR = 7;
  public int JJTINITIATEFOR = 8;
  public int JJTENDFOR = 9;
  public int JJTITERATEFOR = 10;
  public int JJTCOMPAREVALUE = 11;
  public int JJTWHILE = 12;
  public int JJTIF = 13;
  public int JJTELSE = 14;
  public int JJTPRINT = 15;
  public int JJTRETURN = 16;
  public int JJTSOMA = 17;
  public int JJTSUBTRACAO = 18;
  public int JJTMULTIPLICACAO = 19;
  public int JJTDIVISAO = 20;
  public int JJTOPERACAORECURSIVA = 21;
  public int JJTOPERACAO = 22;
  public int JJTID = 23;
  public int JJTTOKENATRIBUICAO = 24;


  public String[] jjtNodeName = {
    "MAIN",
    "TOKENCOMPARADOR",
    "TYPE",
    "COMANDOS",
    "VAR",
    "IDORVALUE",
    "FOR",
    "PARAMETERSFOR",
    "INITIATEFOR",
    "ENDFOR",
    "ITERATEFOR",
    "COMPAREVALUE",
    "WHILE",
    "IF",
    "ELSE",
    "PRINT",
    "RETURN",
    "SOMA",
    "SUBTRACAO",
    "MULTIPLICACAO",
    "DIVISAO",
    "OPERACAORECURSIVA",
    "OPERACAO",
    "ID",
    "TOKENATRIBUICAO",
  };
}
/* JavaCC - OriginalChecksum=b20358818fcf8ad521499de63ac79094 (do not edit this line) */
